### ISSUE TITLE
Добавить личный кабинет пользователя

### ISSUE THREAD

**Issue by IgorPetrov-13** [tomq29/OurNotes#15]
- [x] Личный кабинет
- [x] Информация о пользователе
- [x]  Кнопка "создать пару"
- [x] Приглашения от других пользователей
- [x] есть пара есть и она активна, пользователь в профиле должен видеть только пару. кнопок на добавление и входящих не должно быть
- [x] добавить ее в роуты
- [x] расширить Slice юзера. добавить туда Pair

- [x] нужно добавить выбор предпочитаемого цвета

**Comment by tomq29** [comment]
- [ ] Добавить выбор предпочитаемого цвета в select

**Comment by tomq29** [comment]
- [ ] есть пара есть и она активна, пользователь в профиле должен видеть только пару. кнопок на добавление и входящих не должно быть
- [ ] нужно добавить выбор предпочитаемого цвета
